[{"ContainerToolsException.Message":"Při analýze vnořeného oddílu projektu v souboru řešení došlo k chybě. Projekt s GUID {67C55FC5-A632-4DB0-9CB7-D34C3545E15A} je uveden jako vnořený pod projektem {3A409DED-66BF-4D93-87A3-812F61C04AF5}, ale v daném řešení neexistuje.  /Users/petr/Projects/TaskTracker/TaskTracker/src/TaskTracker.sln","ContainerToolsException.ErrorCode":"CTC1000","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.Build.Exceptions.InvalidProjectFileException: Při analýze vnořeného oddílu projektu v souboru řešení došlo k chybě. Projekt s GUID {67C55FC5-A632-4DB0-9CB7-D34C3545E15A} je uveden jako vnořený pod projektem {3A409DED-66BF-4D93-87A3-812F61C04AF5}, ale v daném řešení neexistuje.  /Users/petr/Projects/TaskTracker/TaskTracker/src/TaskTracker.sln\n   at Microsoft.Build.Shared.ProjectFileErrorUtilities.VerifyThrowInvalidProjectFile(Boolean condition, String errorSubCategoryResourceName, BuildEventFileInfo projectFile, Exception innerException, String resourceName, Object[] args)\n   at Microsoft.Build.Construction.SolutionFile.ParseNestedProjects()\n   at Microsoft.Build.Construction.SolutionFile.ParseSolution()\n   at Microsoft.Build.Construction.SolutionFile.ParseSolutionFile()\n   at Microsoft.Build.Construction.SolutionFile.Parse(String solutionFile)\n   at Microsoft.Docker.BuildTasks.GetServiceReferences.ExecuteCoreAsync(DockerBuildTaskContext context)\n   at Microsoft.Docker.BuildTasks.DockerBuildTask.ExecuteAsync(DockerBuildTaskContext context)"},{"ContainerToolsException.Message":"Při analýze vnořeného oddílu projektu v souboru řešení došlo k chybě. Projekt s GUID {67C55FC5-A632-4DB0-9CB7-D34C3545E15A} je uveden jako vnořený pod projektem {3A409DED-66BF-4D93-87A3-812F61C04AF5}, ale v daném řešení neexistuje.  /Users/petr/Projects/TaskTracker/TaskTracker/src/TaskTracker.sln","ContainerToolsException.ErrorCode":"CTC1000","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.Build.Exceptions.InvalidProjectFileException: Při analýze vnořeného oddílu projektu v souboru řešení došlo k chybě. Projekt s GUID {67C55FC5-A632-4DB0-9CB7-D34C3545E15A} je uveden jako vnořený pod projektem {3A409DED-66BF-4D93-87A3-812F61C04AF5}, ale v daném řešení neexistuje.  /Users/petr/Projects/TaskTracker/TaskTracker/src/TaskTracker.sln\n   at Microsoft.Build.Shared.ProjectFileErrorUtilities.VerifyThrowInvalidProjectFile(Boolean condition, String errorSubCategoryResourceName, BuildEventFileInfo projectFile, Exception innerException, String resourceName, Object[] args)\n   at Microsoft.Build.Construction.SolutionFile.ParseNestedProjects()\n   at Microsoft.Build.Construction.SolutionFile.ParseSolution()\n   at Microsoft.Build.Construction.SolutionFile.ParseSolutionFile()\n   at Microsoft.Build.Construction.SolutionFile.Parse(String solutionFile)\n   at Microsoft.Docker.BuildTasks.GetServiceReferences.ExecuteCoreAsync(DockerBuildTaskContext context)\n   at Microsoft.Docker.BuildTasks.DockerBuildTask.ExecuteAsync(DockerBuildTaskContext context)"},{"ContainerToolsException.Message":"Při analýze vnořeného oddílu projektu v souboru řešení došlo k chybě. Projekt s GUID {67C55FC5-A632-4DB0-9CB7-D34C3545E15A} je uveden jako vnořený pod projektem {3A409DED-66BF-4D93-87A3-812F61C04AF5}, ale v daném řešení neexistuje.  /Users/petr/Projects/TaskTracker/TaskTracker/src/TaskTracker.sln","ContainerToolsException.ErrorCode":"CTC1000","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.Build.Exceptions.InvalidProjectFileException: Při analýze vnořeného oddílu projektu v souboru řešení došlo k chybě. Projekt s GUID {67C55FC5-A632-4DB0-9CB7-D34C3545E15A} je uveden jako vnořený pod projektem {3A409DED-66BF-4D93-87A3-812F61C04AF5}, ale v daném řešení neexistuje.  /Users/petr/Projects/TaskTracker/TaskTracker/src/TaskTracker.sln\n   at Microsoft.Build.Shared.ProjectFileErrorUtilities.VerifyThrowInvalidProjectFile(Boolean condition, String errorSubCategoryResourceName, BuildEventFileInfo projectFile, Exception innerException, String resourceName, Object[] args)\n   at Microsoft.Build.Construction.SolutionFile.ParseNestedProjects()\n   at Microsoft.Build.Construction.SolutionFile.ParseSolution()\n   at Microsoft.Build.Construction.SolutionFile.ParseSolutionFile()\n   at Microsoft.Build.Construction.SolutionFile.Parse(String solutionFile)\n   at Microsoft.Docker.BuildTasks.GetServiceReferences.ExecuteCoreAsync(DockerBuildTaskContext context)\n   at Microsoft.Docker.BuildTasks.DockerBuildTask.ExecuteAsync(DockerBuildTaskContext context)"},{"ContainerToolsException.Message":"Při analýze vnořeného oddílu projektu v souboru řešení došlo k chybě. Projekt s GUID {67C55FC5-A632-4DB0-9CB7-D34C3545E15A} je uveden jako vnořený pod projektem {3A409DED-66BF-4D93-87A3-812F61C04AF5}, ale v daném řešení neexistuje.  /Users/petr/Projects/TaskTracker/TaskTracker/src/TaskTracker.sln","ContainerToolsException.ErrorCode":"CTC1000","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.Build.Exceptions.InvalidProjectFileException: Při analýze vnořeného oddílu projektu v souboru řešení došlo k chybě. Projekt s GUID {67C55FC5-A632-4DB0-9CB7-D34C3545E15A} je uveden jako vnořený pod projektem {3A409DED-66BF-4D93-87A3-812F61C04AF5}, ale v daném řešení neexistuje.  /Users/petr/Projects/TaskTracker/TaskTracker/src/TaskTracker.sln\n   at Microsoft.Build.Shared.ProjectFileErrorUtilities.VerifyThrowInvalidProjectFile(Boolean condition, String errorSubCategoryResourceName, BuildEventFileInfo projectFile, Exception innerException, String resourceName, Object[] args)\n   at Microsoft.Build.Construction.SolutionFile.ParseNestedProjects()\n   at Microsoft.Build.Construction.SolutionFile.ParseSolution()\n   at Microsoft.Build.Construction.SolutionFile.ParseSolutionFile()\n   at Microsoft.Build.Construction.SolutionFile.Parse(String solutionFile)\n   at Microsoft.Docker.BuildTasks.GetServiceReferences.ExecuteCoreAsync(DockerBuildTaskContext context)\n   at Microsoft.Docker.BuildTasks.DockerBuildTask.ExecuteAsync(DockerBuildTaskContext context)"},{"ContainerToolsException.Message":"Při analýze vnořeného oddílu projektu v souboru řešení došlo k chybě. Projekt s GUID {67C55FC5-A632-4DB0-9CB7-D34C3545E15A} je uveden jako vnořený pod projektem {3A409DED-66BF-4D93-87A3-812F61C04AF5}, ale v daném řešení neexistuje.  /Users/petr/Projects/TaskTracker/TaskTracker/src/TaskTracker.sln","ContainerToolsException.ErrorCode":"CTC1000","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.Build.Exceptions.InvalidProjectFileException: Při analýze vnořeného oddílu projektu v souboru řešení došlo k chybě. Projekt s GUID {67C55FC5-A632-4DB0-9CB7-D34C3545E15A} je uveden jako vnořený pod projektem {3A409DED-66BF-4D93-87A3-812F61C04AF5}, ale v daném řešení neexistuje.  /Users/petr/Projects/TaskTracker/TaskTracker/src/TaskTracker.sln\n   at Microsoft.Build.Shared.ProjectFileErrorUtilities.VerifyThrowInvalidProjectFile(Boolean condition, String errorSubCategoryResourceName, BuildEventFileInfo projectFile, Exception innerException, String resourceName, Object[] args)\n   at Microsoft.Build.Construction.SolutionFile.ParseNestedProjects()\n   at Microsoft.Build.Construction.SolutionFile.ParseSolution()\n   at Microsoft.Build.Construction.SolutionFile.ParseSolutionFile()\n   at Microsoft.Build.Construction.SolutionFile.Parse(String solutionFile)\n   at Microsoft.Docker.BuildTasks.GetServiceReferences.ExecuteCoreAsync(DockerBuildTaskContext context)\n   at Microsoft.Docker.BuildTasks.DockerBuildTask.ExecuteAsync(DockerBuildTaskContext context)"},{"ContainerToolsException.Message":"Při analýze vnořeného oddílu projektu v souboru řešení došlo k chybě. Projekt s GUID {67C55FC5-A632-4DB0-9CB7-D34C3545E15A} je uveden jako vnořený pod projektem {3A409DED-66BF-4D93-87A3-812F61C04AF5}, ale v daném řešení neexistuje.  /Users/petr/Projects/TaskTracker/TaskTracker/src/TaskTracker.sln","ContainerToolsException.ErrorCode":"CTC1000","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.Build.Exceptions.InvalidProjectFileException: Při analýze vnořeného oddílu projektu v souboru řešení došlo k chybě. Projekt s GUID {67C55FC5-A632-4DB0-9CB7-D34C3545E15A} je uveden jako vnořený pod projektem {3A409DED-66BF-4D93-87A3-812F61C04AF5}, ale v daném řešení neexistuje.  /Users/petr/Projects/TaskTracker/TaskTracker/src/TaskTracker.sln\n   at Microsoft.Build.Shared.ProjectFileErrorUtilities.VerifyThrowInvalidProjectFile(Boolean condition, String errorSubCategoryResourceName, BuildEventFileInfo projectFile, Exception innerException, String resourceName, Object[] args)\n   at Microsoft.Build.Construction.SolutionFile.ParseNestedProjects()\n   at Microsoft.Build.Construction.SolutionFile.ParseSolution()\n   at Microsoft.Build.Construction.SolutionFile.ParseSolutionFile()\n   at Microsoft.Build.Construction.SolutionFile.Parse(String solutionFile)\n   at Microsoft.Docker.BuildTasks.GetServiceReferences.ExecuteCoreAsync(DockerBuildTaskContext context)\n   at Microsoft.Docker.BuildTasks.DockerBuildTask.ExecuteAsync(DockerBuildTaskContext context)"},{"ContainerToolsException.Message":"Při analýze vnořeného oddílu projektu v souboru řešení došlo k chybě. Projekt s GUID {67C55FC5-A632-4DB0-9CB7-D34C3545E15A} je uveden jako vnořený pod projektem {3A409DED-66BF-4D93-87A3-812F61C04AF5}, ale v daném řešení neexistuje.  /Users/petr/Projects/TaskTracker/TaskTracker/src/TaskTracker.sln","ContainerToolsException.ErrorCode":"CTC1000","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.Build.Exceptions.InvalidProjectFileException: Při analýze vnořeného oddílu projektu v souboru řešení došlo k chybě. Projekt s GUID {67C55FC5-A632-4DB0-9CB7-D34C3545E15A} je uveden jako vnořený pod projektem {3A409DED-66BF-4D93-87A3-812F61C04AF5}, ale v daném řešení neexistuje.  /Users/petr/Projects/TaskTracker/TaskTracker/src/TaskTracker.sln\n   at Microsoft.Build.Shared.ProjectFileErrorUtilities.VerifyThrowInvalidProjectFile(Boolean condition, String errorSubCategoryResourceName, BuildEventFileInfo projectFile, Exception innerException, String resourceName, Object[] args)\n   at Microsoft.Build.Construction.SolutionFile.ParseNestedProjects()\n   at Microsoft.Build.Construction.SolutionFile.ParseSolution()\n   at Microsoft.Build.Construction.SolutionFile.ParseSolutionFile()\n   at Microsoft.Build.Construction.SolutionFile.Parse(String solutionFile)\n   at Microsoft.Docker.BuildTasks.GetServiceReferences.ExecuteCoreAsync(DockerBuildTaskContext context)\n   at Microsoft.Docker.BuildTasks.DockerBuildTask.ExecuteAsync(DockerBuildTaskContext context)"},{"ContainerToolsException.Message":"Při analýze vnořeného oddílu projektu v souboru řešení došlo k chybě. Projekt s GUID {67C55FC5-A632-4DB0-9CB7-D34C3545E15A} je uveden jako vnořený pod projektem {3A409DED-66BF-4D93-87A3-812F61C04AF5}, ale v daném řešení neexistuje.  /Users/petr/Projects/TaskTracker/TaskTracker/src/TaskTracker.sln","ContainerToolsException.ErrorCode":"CTC1000","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.Build.Exceptions.InvalidProjectFileException: Při analýze vnořeného oddílu projektu v souboru řešení došlo k chybě. Projekt s GUID {67C55FC5-A632-4DB0-9CB7-D34C3545E15A} je uveden jako vnořený pod projektem {3A409DED-66BF-4D93-87A3-812F61C04AF5}, ale v daném řešení neexistuje.  /Users/petr/Projects/TaskTracker/TaskTracker/src/TaskTracker.sln\n   at Microsoft.Build.Shared.ProjectFileErrorUtilities.VerifyThrowInvalidProjectFile(Boolean condition, String errorSubCategoryResourceName, BuildEventFileInfo projectFile, Exception innerException, String resourceName, Object[] args)\n   at Microsoft.Build.Construction.SolutionFile.ParseNestedProjects()\n   at Microsoft.Build.Construction.SolutionFile.ParseSolution()\n   at Microsoft.Build.Construction.SolutionFile.ParseSolutionFile()\n   at Microsoft.Build.Construction.SolutionFile.Parse(String solutionFile)\n   at Microsoft.Docker.BuildTasks.GetServiceReferences.ExecuteCoreAsync(DockerBuildTaskContext context)\n   at Microsoft.Docker.BuildTasks.DockerBuildTask.ExecuteAsync(DockerBuildTaskContext context)"},{"ContainerToolsException.Message":"Při analýze vnořeného oddílu projektu v souboru řešení došlo k chybě. Projekt s GUID {67C55FC5-A632-4DB0-9CB7-D34C3545E15A} je uveden jako vnořený pod projektem {3A409DED-66BF-4D93-87A3-812F61C04AF5}, ale v daném řešení neexistuje.  /Users/petr/Projects/TaskTracker/TaskTracker/src/TaskTracker.sln","ContainerToolsException.ErrorCode":"CTC1000","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.Build.Exceptions.InvalidProjectFileException: Při analýze vnořeného oddílu projektu v souboru řešení došlo k chybě. Projekt s GUID {67C55FC5-A632-4DB0-9CB7-D34C3545E15A} je uveden jako vnořený pod projektem {3A409DED-66BF-4D93-87A3-812F61C04AF5}, ale v daném řešení neexistuje.  /Users/petr/Projects/TaskTracker/TaskTracker/src/TaskTracker.sln\n   at Microsoft.Build.Shared.ProjectFileErrorUtilities.VerifyThrowInvalidProjectFile(Boolean condition, String errorSubCategoryResourceName, BuildEventFileInfo projectFile, Exception innerException, String resourceName, Object[] args)\n   at Microsoft.Build.Construction.SolutionFile.ParseNestedProjects()\n   at Microsoft.Build.Construction.SolutionFile.ParseSolution()\n   at Microsoft.Build.Construction.SolutionFile.ParseSolutionFile()\n   at Microsoft.Build.Construction.SolutionFile.Parse(String solutionFile)\n   at Microsoft.Docker.BuildTasks.GetServiceReferences.ExecuteCoreAsync(DockerBuildTaskContext context)\n   at Microsoft.Docker.BuildTasks.DockerBuildTask.ExecuteAsync(DockerBuildTaskContext context)"},{"ContainerToolsException.Message":"Při analýze vnořeného oddílu projektu v souboru řešení došlo k chybě. Projekt s GUID {67C55FC5-A632-4DB0-9CB7-D34C3545E15A} je uveden jako vnořený pod projektem {3A409DED-66BF-4D93-87A3-812F61C04AF5}, ale v daném řešení neexistuje.  /Users/petr/Projects/TaskTracker/TaskTracker/src/TaskTracker.sln","ContainerToolsException.ErrorCode":"CTC1000","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.Build.Exceptions.InvalidProjectFileException: Při analýze vnořeného oddílu projektu v souboru řešení došlo k chybě. Projekt s GUID {67C55FC5-A632-4DB0-9CB7-D34C3545E15A} je uveden jako vnořený pod projektem {3A409DED-66BF-4D93-87A3-812F61C04AF5}, ale v daném řešení neexistuje.  /Users/petr/Projects/TaskTracker/TaskTracker/src/TaskTracker.sln\n   at Microsoft.Build.Shared.ProjectFileErrorUtilities.VerifyThrowInvalidProjectFile(Boolean condition, String errorSubCategoryResourceName, BuildEventFileInfo projectFile, Exception innerException, String resourceName, Object[] args)\n   at Microsoft.Build.Construction.SolutionFile.ParseNestedProjects()\n   at Microsoft.Build.Construction.SolutionFile.ParseSolution()\n   at Microsoft.Build.Construction.SolutionFile.ParseSolutionFile()\n   at Microsoft.Build.Construction.SolutionFile.Parse(String solutionFile)\n   at Microsoft.Docker.BuildTasks.GetServiceReferences.ExecuteCoreAsync(DockerBuildTaskContext context)\n   at Microsoft.Docker.BuildTasks.DockerBuildTask.ExecuteAsync(DockerBuildTaskContext context)"},{"ContainerToolsException.Message":"Při analýze vnořeného oddílu projektu v souboru řešení došlo k chybě. Projekt s GUID {67C55FC5-A632-4DB0-9CB7-D34C3545E15A} je uveden jako vnořený pod projektem {3A409DED-66BF-4D93-87A3-812F61C04AF5}, ale v daném řešení neexistuje.  /Users/petr/Projects/TaskTracker/TaskTracker/src/TaskTracker.sln","ContainerToolsException.ErrorCode":"CTC1000","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.Build.Exceptions.InvalidProjectFileException: Při analýze vnořeného oddílu projektu v souboru řešení došlo k chybě. Projekt s GUID {67C55FC5-A632-4DB0-9CB7-D34C3545E15A} je uveden jako vnořený pod projektem {3A409DED-66BF-4D93-87A3-812F61C04AF5}, ale v daném řešení neexistuje.  /Users/petr/Projects/TaskTracker/TaskTracker/src/TaskTracker.sln\n   at Microsoft.Build.Shared.ProjectFileErrorUtilities.VerifyThrowInvalidProjectFile(Boolean condition, String errorSubCategoryResourceName, BuildEventFileInfo projectFile, Exception innerException, String resourceName, Object[] args)\n   at Microsoft.Build.Construction.SolutionFile.ParseNestedProjects()\n   at Microsoft.Build.Construction.SolutionFile.ParseSolution()\n   at Microsoft.Build.Construction.SolutionFile.ParseSolutionFile()\n   at Microsoft.Build.Construction.SolutionFile.Parse(String solutionFile)\n   at Microsoft.Docker.BuildTasks.GetServiceReferences.ExecuteCoreAsync(DockerBuildTaskContext context)\n   at Microsoft.Docker.BuildTasks.DockerBuildTask.ExecuteAsync(DockerBuildTaskContext context)"},{"ContainerToolsException.Message":"Při analýze vnořeného oddílu projektu v souboru řešení došlo k chybě. Projekt s GUID {8E5AED63-602B-444E-B062-0FBF3690EF7D} je uveden jako vnořený pod projektem {3A409DED-66BF-4D93-87A3-812F61C04AF5}, ale v daném řešení neexistuje.  /Users/petr/Projects/TaskTracker/TaskTracker/src/TaskTracker.sln","ContainerToolsException.ErrorCode":"CTC1000","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.Build.Exceptions.InvalidProjectFileException: Při analýze vnořeného oddílu projektu v souboru řešení došlo k chybě. Projekt s GUID {8E5AED63-602B-444E-B062-0FBF3690EF7D} je uveden jako vnořený pod projektem {3A409DED-66BF-4D93-87A3-812F61C04AF5}, ale v daném řešení neexistuje.  /Users/petr/Projects/TaskTracker/TaskTracker/src/TaskTracker.sln\n   at Microsoft.Build.Shared.ProjectFileErrorUtilities.VerifyThrowInvalidProjectFile(Boolean condition, String errorSubCategoryResourceName, BuildEventFileInfo projectFile, Exception innerException, String resourceName, Object[] args)\n   at Microsoft.Build.Construction.SolutionFile.ParseNestedProjects()\n   at Microsoft.Build.Construction.SolutionFile.ParseSolution()\n   at Microsoft.Build.Construction.SolutionFile.ParseSolutionFile()\n   at Microsoft.Build.Construction.SolutionFile.Parse(String solutionFile)\n   at Microsoft.Docker.BuildTasks.GetServiceReferences.ExecuteCoreAsync(DockerBuildTaskContext context)\n   at Microsoft.Docker.BuildTasks.DockerBuildTask.ExecuteAsync(DockerBuildTaskContext context)"},{"ContainerToolsException.Message":"Při analýze vnořeného oddílu projektu v souboru řešení došlo k chybě. Projekt s GUID {3460E576-2D2B-49D2-B43A-B31BE494FB19} je uveden jako vnořený pod projektem {3A409DED-66BF-4D93-87A3-812F61C04AF5}, ale v daném řešení neexistuje.  /Users/petr/Projects/TaskTracker/TaskTracker/src/TaskTracker.sln","ContainerToolsException.ErrorCode":"CTC1000","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.Build.Exceptions.InvalidProjectFileException: Při analýze vnořeného oddílu projektu v souboru řešení došlo k chybě. Projekt s GUID {3460E576-2D2B-49D2-B43A-B31BE494FB19} je uveden jako vnořený pod projektem {3A409DED-66BF-4D93-87A3-812F61C04AF5}, ale v daném řešení neexistuje.  /Users/petr/Projects/TaskTracker/TaskTracker/src/TaskTracker.sln\n   at Microsoft.Build.Shared.ProjectFileErrorUtilities.VerifyThrowInvalidProjectFile(Boolean condition, String errorSubCategoryResourceName, BuildEventFileInfo projectFile, Exception innerException, String resourceName, Object[] args)\n   at Microsoft.Build.Construction.SolutionFile.ParseNestedProjects()\n   at Microsoft.Build.Construction.SolutionFile.ParseSolution()\n   at Microsoft.Build.Construction.SolutionFile.ParseSolutionFile()\n   at Microsoft.Build.Construction.SolutionFile.Parse(String solutionFile)\n   at Microsoft.Docker.BuildTasks.GetServiceReferences.ExecuteCoreAsync(DockerBuildTaskContext context)\n   at Microsoft.Docker.BuildTasks.DockerBuildTask.ExecuteAsync(DockerBuildTaskContext context)"},{"ContainerToolsException.Message":"Při analýze vnořeného oddílu projektu v souboru řešení došlo k chybě. Projekt s GUID {11EB19E9-A943-4AE2-9C1A-C4F1FDE20E9E} je uveden jako vnořený pod projektem {3A409DED-66BF-4D93-87A3-812F61C04AF5}, ale v daném řešení neexistuje.  /Users/petr/Projects/TaskTracker/TaskTracker/src/TaskTracker.sln","ContainerToolsException.ErrorCode":"CTC1000","ContainerToolsException.StackTrace":"","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.Build.Exceptions.InvalidProjectFileException: Při analýze vnořeného oddílu projektu v souboru řešení došlo k chybě. Projekt s GUID {11EB19E9-A943-4AE2-9C1A-C4F1FDE20E9E} je uveden jako vnořený pod projektem {3A409DED-66BF-4D93-87A3-812F61C04AF5}, ale v daném řešení neexistuje.  /Users/petr/Projects/TaskTracker/TaskTracker/src/TaskTracker.sln\n   at Microsoft.Build.Shared.ProjectFileErrorUtilities.VerifyThrowInvalidProjectFile(Boolean condition, String errorSubCategoryResourceName, BuildEventFileInfo projectFile, Exception innerException, String resourceName, Object[] args)\n   at Microsoft.Build.Construction.SolutionFile.ParseNestedProjects()\n   at Microsoft.Build.Construction.SolutionFile.ParseSolution()\n   at Microsoft.Build.Construction.SolutionFile.ParseSolutionFile()\n   at Microsoft.Build.Construction.SolutionFile.Parse(String solutionFile)\n   at Microsoft.Docker.BuildTasks.GetServiceReferences.ExecuteCoreAsync(DockerBuildTaskContext context)\n   at Microsoft.Docker.BuildTasks.DockerBuildTask.ExecuteAsync(DockerBuildTaskContext context)"},{"ContainerToolsException.Message":"ERROR: for taskservice.api  Cannot create container for service taskservice.api: Conflict. The container name \"/TaskService.API\" is already in use by container \"9b4a716a6cd4bcfebb91976423ffbbb4f588edfc0321f556ee254b8b9c6dde6c\". You have to remove (or rename) that container to be able to reuse that name. Pokud se chyba bude opakovat, zkuste restartovat Docker Desktop.","ContainerToolsException.ErrorCode":"DT1001","ContainerToolsException.StackTrace":"   at Microsoft.Docker.DockerWorkspace.PrepareForLaunchAsync(DockerDevelopmentMode dockerDevelopmentMode, Boolean noBuild, IDockerLogger logger, String dockerComposeUpArguments, CancellationToken cancellationToken)\n   at Microsoft.Docker.BuildTasks.PrepareForLaunch.ExecuteCoreAsync(DockerBuildTaskContext context)\n   at Microsoft.Docker.BuildTasks.DockerBuildTask.ExecuteAsync(DockerBuildTaskContext context)","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: ERROR: for taskservice.api  Cannot create container for service taskservice.api: Conflict. The container name \"/TaskService.API\" is already in use by container \"9b4a716a6cd4bcfebb91976423ffbbb4f588edfc0321f556ee254b8b9c6dde6c\". You have to remove (or rename) that container to be able to reuse that name.\n   at Microsoft.Docker.DockerWorkspace.PrepareForLaunchAsync(DockerDevelopmentMode dockerDevelopmentMode, Boolean noBuild, IDockerLogger logger, String dockerComposeUpArguments, CancellationToken cancellationToken)\nKód chyby: DT1001\nZávažnost: Error\nPříkazový řádek: docker-compose -f \"/Users/petr/Projects/TaskTracker/TaskTracker/src/docker-compose.yml\" -f \"/Users/petr/Projects/TaskTracker/TaskTracker/src/docker-compose.override.yml\" -f \"/Users/petr/Projects/TaskTracker/TaskTracker/src/obj/Docker/docker-compose.vs.debug.g.yml\" -p dockercompose770814784130231965 --ansi never up -d --build --remove-orphans\nUkončovací kód příkazu: 1\nVýstup příkazu: \nChyba příkazu: Creating network \"dockercompose770814784130231965_default\" with the default driver\nBuilding taskservice.api\n#1 [internal] load build definition from Dockerfile\n#1 sha256:a5c0abc93b923293db06a65983c5c4f8caace8856eb40df26ba0ad6d06dcfc30\n#1 transferring dockerfile: 37B done\n#1 DONE 0.0s\n#2 [internal] load .dockerignore\n#2 sha256:deefac69c62f682d9e9401ac3d3eab04690684343907492beb3b79c9c3e2a8fd\n#2 transferring context: 35B done\n#2 DONE 0.0s\n#3 [internal] load metadata for mcr.microsoft.com/dotnet/aspnet:7.0\n#3 sha256:e832ab57eb21a07d207c79335170db3f99eab7c10ae45bfee4e878461030d1cc\n#3 DONE 0.1s\n#4 [base 1/2] FROM mcr.microsoft.com/dotnet/aspnet:7.0@sha256:3fbe582ae85438ca0b0095f7926b0613a3645afb3f1845daddf901855e9207f4\n#4 sha256:e2f8093ac1548bfa173609086b28724a8ca6510fbd1728faa840dcafc1338b45\n#4 DONE 0.0s\n#5 [base 2/2] WORKDIR /app\n#5 sha256:6671e9680c60a50c51969460d5a29ebac728667bcaebddc8b3d2aab2f6a83537\n#5 CACHED\n#6 exporting to image\n#6 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00\n#6 exporting layers done\n#6 writing image sha256:b70180193805dbd59acdfaaf2d53d3ae36b1d27539c43b95f58b90f8311575df done\n#6 naming to docker.io/library/taskservice:dev done\n#6 DONE 0.0s\nUse 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them\nCreating taskdb ... \nCreating TaskService.API ... \nCreating taskdb          ... error\nERROR: for taskdb  Cannot create container for service taskdb: Conflict. The container name \"/taskdb\" is already in use by container \"861868dc17fb1221d63abd419cc91c40da07c13b8827fb6b24a7271d6d3a3713\". You have to remove (or rename) that container to be able to reuse that name.\nCreating TaskService.API ... error\nERROR: for TaskService.API  Cannot create container for service taskservice.api: Conflict. The container name \"/TaskService.API\" is already in use by container \"9b4a716a6cd4bcfebb91976423ffbbb4f588edfc0321f556ee254b8b9c6dde6c\". You have to remove (or rename) that container to be able to reuse that name.\nERROR: for taskdb  Cannot create container for service taskdb: Conflict. The container name \"/taskdb\" is already in use by container \"861868dc17fb1221d63abd419cc91c40da07c13b8827fb6b24a7271d6d3a3713\". You have to remove (or rename) that container to be able to reuse that name.\nERROR: for taskservice.api  Cannot create container for service taskservice.api: Conflict. The container name \"/TaskService.API\" is already in use by container \"9b4a716a6cd4bcfebb91976423ffbbb4f588edfc0321f556ee254b8b9c6dde6c\". You have to remove (or rename) that container to be able to reuse that name.\nEncountered errors while bringing up the project.\n"},{"ContainerToolsException.Message":"ERROR: for taskdb  Cannot start service taskdb: driver failed programming external connectivity on endpoint taskdb (623f80c25e4172e26c989ba23339b8442d32daf9f86390b9ee24f3dc5734d553): Bind for 0.0.0.0:1433 failed: port is already allocated Pokud se chyba bude opakovat, zkuste restartovat Docker Desktop.","ContainerToolsException.ErrorCode":"DT1001","ContainerToolsException.StackTrace":"   at Microsoft.Docker.DockerWorkspace.PrepareForLaunchAsync(DockerDevelopmentMode dockerDevelopmentMode, Boolean noBuild, IDockerLogger logger, String dockerComposeUpArguments, CancellationToken cancellationToken)\n   at Microsoft.Docker.BuildTasks.PrepareForLaunch.ExecuteCoreAsync(DockerBuildTaskContext context)\n   at Microsoft.Docker.BuildTasks.DockerBuildTask.ExecuteAsync(DockerBuildTaskContext context)","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.InnerException":"Microsoft.VisualStudio.Containers.Tools.Common.ContainerToolsException: ERROR: for taskdb  Cannot start service taskdb: driver failed programming external connectivity on endpoint taskdb (623f80c25e4172e26c989ba23339b8442d32daf9f86390b9ee24f3dc5734d553): Bind for 0.0.0.0:1433 failed: port is already allocated\n   at Microsoft.Docker.DockerWorkspace.PrepareForLaunchAsync(DockerDevelopmentMode dockerDevelopmentMode, Boolean noBuild, IDockerLogger logger, String dockerComposeUpArguments, CancellationToken cancellationToken)\nKód chyby: DT1001\nZávažnost: Error\nPříkazový řádek: docker-compose -f \"/Users/petr/Projects/TaskTracker/TaskTracker/src/docker-compose.yml\" -f \"/Users/petr/Projects/TaskTracker/TaskTracker/src/docker-compose.override.yml\" -f \"/Users/petr/Projects/TaskTracker/TaskTracker/src/obj/Docker/docker-compose.vs.debug.g.yml\" -p dockercompose770814784130231965 --ansi never up -d --build --remove-orphans\nUkončovací kód příkazu: 1\nVýstup příkazu: \nChyba příkazu: Building taskservice.api\n#1 [internal] load build definition from Dockerfile\n#1 sha256:2a7587fbf6db0b89c37b1851cdd33a5224d493229324839079d775c417c9ddfa\n#1 transferring dockerfile: 37B done\n#1 DONE 0.0s\n#2 [internal] load .dockerignore\n#2 sha256:26a88a0c2a3dc9c5c972f6ab7620fee751a74f29bd8d0651d937b5e80d5781ce\n#2 transferring context: 35B done\n#2 DONE 0.0s\n#3 [internal] load metadata for mcr.microsoft.com/dotnet/aspnet:7.0\n#3 sha256:e832ab57eb21a07d207c79335170db3f99eab7c10ae45bfee4e878461030d1cc\n#3 DONE 0.2s\n#4 [base 1/2] FROM mcr.microsoft.com/dotnet/aspnet:7.0@sha256:3fbe582ae85438ca0b0095f7926b0613a3645afb3f1845daddf901855e9207f4\n#4 sha256:e2f8093ac1548bfa173609086b28724a8ca6510fbd1728faa840dcafc1338b45\n#4 DONE 0.0s\n#5 [base 2/2] WORKDIR /app\n#5 sha256:6671e9680c60a50c51969460d5a29ebac728667bcaebddc8b3d2aab2f6a83537\n#5 CACHED\n#6 exporting to image\n#6 sha256:e8c613e07b0b7ff33893b694f7759a10d42e180f2b4dc349fb57dc6b71dcab00\n#6 exporting layers done\n#6 writing image sha256:b70180193805dbd59acdfaaf2d53d3ae36b1d27539c43b95f58b90f8311575df done\n#6 naming to docker.io/library/taskservice:dev done\n#6 DONE 0.0s\nUse 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them\nCreating taskdb ... \nCreating TaskService.API ... \nHost is already in use by another container\nCreating taskdb          ... error\nERROR: for taskdb  Cannot start service taskdb: driver failed programming external connectivity on endpoint taskdb (623f80c25e4172e26c989ba23339b8442d32daf9f86390b9ee24f3dc5734d553): Bind for 0.0.0.0:1433 failed: port is already allocated\nCreating TaskService.API ... done\nERROR: for taskdb  Cannot start service taskdb: driver failed programming external connectivity on endpoint taskdb (623f80c25e4172e26c989ba23339b8442d32daf9f86390b9ee24f3dc5734d553): Bind for 0.0.0.0:1433 failed: port is already allocated\nEncountered errors while bringing up the project.\n"}]